### ISSUE TITLE
"participant doing the harassing"

### ISSUE THREAD

**Issue by NikolasE** [python/pycon-code-of-conduct#15]
Step one of reporting is
  "Identifying information (name/badge number) of the participant doing the harassing"

Is there a rationale not to use a wording like "of the accused participant"? The first step in dealing with a situation otherwise already contains the verdict (there is someone who harassed).

**Comment by dianaclarke** [comment]
There's lots of room for improvement. For example, "Report the harassment incident" also assumes the incident in question is "harassment" when in reality these procedures are meant to be guidelines for all sorts of incidents.

**Comment by sigmavirus24** [comment]
@NikolasE in most cases someone will be reporting the fact that they are being harassed (not someone else doing the reporting for them). From that person's perspective "I have to get the identifying information of the person harassing me" because they wouldn't be reporting them otherwise.

This isn't a legal document and the people responsible for handling reports don't automatically assume the other person is guilty.

**Comment by NikolasE** [comment]
"will be reporting the fact that they are being harassed"   They can only report that they think they are harassed.

**Comment by dianaclarke** [comment]
I encourage you consider "the spirit" of these docs, not their literal meaning. Like I said earlier, there's lots of room for improvement. As someone that has fielded a number of Code of Conduct reports, please let me assure you that each report is considered individually with nuance & that these are only guidelines; written by volunteers with limited time.

**Comment by holdenweb** [comment]
How about "the subject(s) of the complaint"?

**Comment by sigmavirus24** [comment]
@holdenweb I feel like you and @NikolasE are trying to make this more legalistic than understandable. As @dianaclarke said, the exact language is unimportant because it's the spirit of the document that people fielding code of conduct complaints will be considering.

Yes there's room for improvement. No, I don't think we need to make this read more like a legal document.

**Comment by ewdurbin** [comment]
we have removed the specificity of harassment with updates for 2018.
